image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
- cd reddit
- bundle install

build_job:
  stage: build
  script:
    - echo 'Building'

deploy_job:
  stage: build
  image: ruby:2.4.2
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.otus.bsv.pp.ua
    auto_stop_in: 20 minutes
  only:
    - branches

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.otus.pp.ua

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
    auto_stop_in: 20 minutes
  only:
    - branches
  except:
    - master


staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.+d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.otus.pp.ua
    auto_stop_in: 1 hour

production:
  stage: production
  when: manual
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://otus.pp.ua
    auto_stop_in: 1 hour
