---
- name: Deploy gitlab
  hosts: gitlab
  become: true
  tasks:
    - name: Create dir for gitlab
      file:
        path: /srv/gitlab
        state: directory

    - name: copy template to docker-host
      template:
        src: templates/gitlab_omni.yml.j2
        dest: /srv/runner/docker-compose.yml

    - name: start docker-compose for gitlab
        community.docker.docker_compose:
          project_src: /srv/gitlab
